// lib/dummyData.js
export const CATEGORIES = [
  { id: "all", icon: "⭐", label: { ar: "الكل", en: "All", de: "Alle", tr: "Hepsi" } },
  { id: "cars", icon: "🚗", label: { ar: "سيارات", en: "Cars", de: "Autos", tr: "Arabalar" } },
  { id: "homes", icon: "🏠", label: { ar: "عقارات", en: "Real estate", de: "Immobilien", tr: "Emlak" } },
  { id: "jobs", icon: "💼", label: { ar: "وظائف", en: "Jobs", de: "Jobs", tr: "İş ilanları" } },
  { id: "electronics", icon: "📱", label: { ar: "إلكترونيات", en: "Electronics", de: "Elektronik", tr: "Elektronik" } },
];

export const LISTINGS = [
  {
    id: 1,
    category: "cars",
    title_ar: "سيارة كيا ريو 2013 بحالة ممتازة",
    title_en: "Kia Rio 2013 in very good condition",
    city: "دمشق",
    city_en: "Damascus",
    price: 320000000,
    currency: "SYP",
    image: null,
  },
  {
    id: 2,
    category: "homes",
    title_ar: "شقة للإيجار في برلين – غرفتان",
    title_en: "2-room flat for rent in Berlin",
    city: "Berlin",
    city_en: "Berlin",
    price: 850,
    currency: "EUR",
    image: null,
  },
  {
    id: 3,
    category: "electronics",
    title_ar: "هاتف سامسونغ A52 مستعمل",
    title_en: "Used Samsung A52",
    city: "إسطنبول",
    city_en: "Istanbul",
    price: 4500,
    currency: "TRY",
    image: null,
  },
  {
    id: 4,
    category: "jobs",
    title_ar: "مطلوب مطوّر ويب (دوام جزئي، عن بُعد)",
    title_en: "Part-time remote web developer",
    city: "حلب",
    city_en: "Aleppo",
    price: 0,
    currency: "",
    image: null,
  },
];
